using MailKit.Security;
using System.ComponentModel.DataAnnotations;

namespace SmtpTester.Models;

public class SmtpTestRequest
{
    [Required]
    public string From { get; set; } = null!;

    [Required]
    public string Host { get; set; } = null!;

    [Required]
    public int Port { get; set; }

    public SecureSocketOptions SecureSocketOption { get; set; } = SecureSocketOptions.StartTls;

    [Required]
    public string UserName { get; set; } = null!;

    [Required]
    public string Password { get; set; } = null!;

    [Required]
    public string[] To { get; set; } = [];

    public string Subject { get; set; } = "SMTP Scout";

    public string Body { get; set; } = "This email was generated by SMTP Scout. If you feel you are not the intended recipient for this email, you can safely ignore it.";

    public IDictionary<string, string> Headers { get; set; } = new Dictionary<string, string>();
}
